---
title: "sfs"
author: "wyy"
date: "2024-02-26"
output: html_document
---


### water

```{r pressure, echo=FALSE}

library(packfor)
library(vegan)


data <- read.csv("E:/wyy/code_project/running_outcome/final_data/SPDB/part0_treat/semdata/sem_sw_s7_au_to_25_avg.csv")
data <- data[, !(colnames(data) %in% c("lon_grid", "lat_grid"))]


print(colnames(data))


Y <- data['value']  
X <- data[, colnames(data) != 'value']

result <- forward.sel(Y, X,R2more = 0.001, alpha = 0.05, Xscale=FALSE, Yscale= FALSE)

print(result)

file_path <- "E:/wyy/code_project/running_outcome/final_data/SPDB/part2_sem/preanalysis/mlr_sws7.csv"
write.csv(result, file = file_path, row.names = FALSE)

 

```
### Biota

```{r pressure, echo=FALSE}

library(packfor)
library(vegan)


data <- read.csv("E:/wyy/code_project/running_outcome/final_data/SPDB/part0_treat/semdata/sem_lr_sws7_au_to_25_avg.csv")
data <- data[, !(colnames(data) %in% c("lon_grid", "lat_grid"))]

print(colnames(data))


Y <- data['value']  
X <- data[, colnames(data) != 'value']  
result <- forward.sel(Y, X,R2more = 0.001, alpha = 0.05, Xscale=FALSE, Yscale= FALSE)

print(result)

file_path <- "E:/wyy/code_project/running_outcome/final_data/SPDB/part2_sem/preanalysis/mlr_lrsws7.csv"
write.csv(result, file = file_path, row.names = FALSE)

```