---
title: "vpm"
author: "wyy"
date: "2024-04-10"
output: html_document
---

### Biota
```{r pressure, echo=FALSE}

df_raw <- read.csv("E:\\wyy\\code_project\\running_outcome\\final_data\\SPDB\\part0_treat\\semdata\\sem_lr_sws7_au_to_25_avg.csv")
meta_data <- read.csv("C:\\Users\\dell\\OneDrive\\file\\meta_data.csv")

vif_data <- read.csv("E:\\wyy\\code_project\\running_outcome\\final_data\\SPDB\\part2_sem\\preanalysis\\vif_sfs_lr_sws7_10_3_2.csv")

list_select <- vif_data$variables
list_select <- c(list_select, 'value')

df_data <- df_raw[, list_select]

library(vegan)

list_1 <- meta_data$var_name[meta_data$var_type3 == 0]
list_2 <- meta_data$var_name[meta_data$var_type3 == 1]
list_3 <- meta_data$var_name[meta_data$var_type3 == 2]
list_4 <- meta_data$var_name[meta_data$var_type3 == 3]

list_col <- colnames(df_data)

X1_cols <- intersect(list_col, list_1)
X2_cols <- intersect(list_col, list_2)
X3_cols <- intersect(list_col, list_3)
X4_cols <- intersect(list_col, list_4)


X1 <- as.data.frame(df_data[, X1_cols])
X2 <- as.data.frame(df_data[, X2_cols])
X3 <- as.data.frame(df_data[, X3_cols])
X4 <- as.data.frame(df_data[, X4_cols])


model <- varpart(df_data$value, X1, X2, X3, X4)

summary(model)



path_str <- file.path("E:", "wyy", "code_project", "running_outcome", "final_fig", "SPDB_lrsw")

#library(ggplot2)
# png(file.path(path_str, "fig3_lrsw_vpm.png") , width = 1200, height = 900, )
#plot(model, Xnames = c("HUM", "ENV", "PFAS", "BIO"), cutoff = 0.01, cex = 3.6, bg = c("#555c6c", "#4f9c8b", "#d77563", "#4d8cbf"),lwd=3, id.size=3.6, alpha=125)

# dev.off()


```

### SURFACE WATER
```{r pressure, echo=FALSE}

df_raw <- read.csv("E:\\wyy\\code_project\\running_outcome\\final_data\\SPDB\\part0_treat\\semdata\\sem_sw_s7_au_to_25_avg.csv")
meta_data <- read.csv("C:\\Users\\dell\\OneDrive\\file\\meta_data.csv")

vif_data <- read.csv("E:\\wyy\\code_project\\running_outcome\\final_data\\SPDB\\part2_sem\\preanalysis\\vif_sfs_sws7_10_3_2.csv")

list_select <- vif_data$variables
list_select <- c(list_select, 'value')

df_data <- df_raw[, list_select]

library(vegan)

list_1 <- meta_data$var_name[meta_data$var_type3 == 0]
list_2 <- meta_data$var_name[meta_data$var_type3 == 1]
list_3 <- meta_data$var_name[meta_data$var_type3 == 2]


list_col <- colnames(df_data)


X1_cols <- intersect(list_col, list_1)
X2_cols <- intersect(list_col, list_2)
X3_cols <- intersect(list_col, list_3)


X1 <- as.data.frame(df_data[, X1_cols])
X2 <- as.data.frame(df_data[, X2_cols])
X3 <- as.data.frame(df_data[, X3_cols])



model <- varpart(df_data$value, X1, X2, X3)

summary(model)


path_str <- file.path("E:", "wyy", "code_project", "running_outcome", "final_fig", "SPDB", "part2_sem", "preanalysis")

library(ggplot2)
svg(file.path(path_str, "fig3_sws7_vpm0826_3_2.svg") , width = 12, height = 9, )
plot(model, Xnames = c("HUM", "ENV", "PFAS"), cutoff = 0.01, cex = 3.6, bg = c("#555c6c", "#4f9c8b", "#d77563"),lwd=3, id.size=3.6, alpha=125)

dev.off()




```

